Vagrant::Config.run do |config| 
	config.vm.define :app do |app_config|
		app_config.vm.customize ["modifyvm", :id, "--name", "app", "--memory", "512"] 
		app_config.vm.box = "precise64"
		app_config.vm.host_name = "app"
		app_config.vm.network :hostonly, "33.33.13.37"
	end
	config.vm.define :db do |db_config|
		db_config.vm.customize ["modifyvm", :id, "--name", "db", "--memory", "512"] 
		db_config.vm.box = "precise64"
		db_config.vm.host_name = "db"
		db_config.vm.network :hostonly, "33.33.13.38"
	 end
end

